### ISSUE TITLE
Error at runtime

### ISSUE THREAD

**Issue by erralb** [SolarFloss/Maze-Solving-and-Generating#1]
Hi, trying to run your program and I get this error : 

```
/web/maze|master ⇒  node index.js 
Rows & Colums(odd number pls): 5
Maze Generated: 3.309ms

/web/maze/generate.js:202
    solver("./output/new_maze.png");
    ^

TypeError: solver is not a function
    at create (/web/maze/generate.js:202:5)
    at create (/web/maze/generate.js:196:5)
    at create (/web/maze/generate.js:196:5)
    at create (/web/maze/generate.js:196:5)
    at create (/web/maze/generate.js:196:5)
    at create (/web/maze/generate.js:196:5)
    at create (/web/maze/generate.js:196:5)
    at create (/web/maze/generate.js:196:5)
    at create (/web/maze/generate.js:196:5)
    at create (/web/maze/generate.js:196:5)
```

I'm not familiar at all with node. I also tried : 

```
/web/maze|master ⇒  npm install
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN maze@1.0.0 No repository field.

removed 1 package in 0.42s

```
Seems like I'm doing something wrong here, could you help me please?
I'm using Node v8.9.1 on Debian 9

**Comment by erralb** [comment]
damn... just had to run : 

`node generate.js `

**Comment by lorem-ipsumm** [comment]
Haha. Sorry I couldn't help. I was asleep. Thanks for bringing this up
though. I'll try and make the instructions more clear on how to run it

**Comment by erralb** [comment]
No worries thanks for the reply.

We have to code different AI algorithms for a university project, so we are going to use your program as a base for new implementations.
I will make a pull request when it's done if you're interested! :)

**Comment by lorem-ipsumm** [comment]
Oh okay that sounds great. Yeah feel free to make the pull request when
you're done. How'd you come across my code by the way?

**Comment by erralb** [comment]
Googling :)
We actually decided on a maze solving game for our project, but we only have to code the AI algorithms... So I was looking for a base to start on, and searched for something with similar words to your project name :)

**Comment by lorem-ipsumm** [comment]
Ah yes of course. Well good luck, and let me know if you run into any
issues regarding my code

**Comment by erralb** [comment]
Thanks will do! :) 
We dont'have much time for the project, but ideally we'd like to implement a user interaction interface so a player can also play against the AIs.

BTW can you give me some light as why even numbers aren't working for the maze generation?

**Comment by lorem-ipsumm** [comment]
I ran into this issue about a month ago and I cannot remember what I did to
fix it. There were numbers that just wouldn't work or something. I'll look
into it and get back to you

**Comment by lorem-ipsumm** [comment]
Oh, I misread your question. I thought numbers just were not working. When you enter an odd number it will in fact generate a maze, but there will be all black tiles on the bottom of the map. I made it so it would place the finish tile in a random white tile on the bottom row, but if they are all black, it never places the finish tile. That's at least what I think is going on.


Here is 52 Rows: <a href="https://imgbb.com/"><img src="https://image.ibb.co/hi16nw/new_maze.png" alt="new_maze" border="0"></a><br />

It's small but you can see that on the bottom there are no available white tiles.


Here is 51 Rows: <a href="https://imgbb.com/"><img src="https://image.ibb.co/i3MT0G/new_maze.png" alt="new_maze" border="0"></a>


There are plenty of white tiles to pick from. This is probably solved in an easy way, I just haven't looked at this project in a while. Hope that helped

**Comment by erralb** [comment]
Cool thanks for the explanation, makes sense :)
