### ISSUE TITLE
Image sizes

### ISSUE THREAD

**Issue by erralb** [SolarFloss/Maze-Solving-and-Generating#2]
Hi again :)

I was wondering how you got your maze screenshot to be "big and clean" ?

The images we're generating are just cols x rows in pixels wide and the result is very small.
I tried the scale() jimp function which make the images bigger but it's still very blurry.

**Comment by lorem-ipsumm** [comment]
Hey,

So the picture I have is just really zoomed in. When I made this, I was using Atom text editor and Windows at the time which let me zoom as far in as I want from inside of the editor so I could take a clear screenshot of individual pixels. I'm not really sure how I'd go about scaling them up nicely. Sorry. You may have to find a way to manually scale the images up.

**Comment by erralb** [comment]
ok thanks :)
I'm zooming but somehow the images are blurry... will try to find a solution!

**Comment by lorem-ipsumm** [comment]
Good luck. If you come across a solution, please let me know. Thanks
